remove unnessecary backslash

diff --git a/autokern b/autokern
--- a/autokern
+++ b/autokern
@@ -24,8 +24,8 @@ done
 
 ### Initialise vars
 type tar gcc make ld depmod perl bc openssl grub-mkconfig mkinitcpio >> /dev/null || { echo "The required programs are not installed, for more information, run 'autokern -h'"; exit; }
-[ -z "$KERNDIR" ] && export KERNDIR="$HOME"\/.cache/autokern
-[ -z "$AUTOKERNCONF" ] && export AUTOKERNCONF="$HOME"\/.config/autokern
+[ -z "$KERNDIR" ] && export KERNDIR="$HOME"/.cache/autokern
+[ -z "$AUTOKERNCONF" ] && export AUTOKERNCONF="$HOME"/.config/autokern
 mkdir -p "$KERNDIR"
 mkdir -p "$AUTOKERNCONF"
 [ ! -f "$AUTOKERNCONF"/config ] && cd "$(dirname "$0")" && cp config.example "$AUTOKERNCONF"/config && . "$AUTOKERNCONF"/config || return
@@ -37,7 +37,7 @@ cd "$KERNDIR" || return
 export KERNVER="$KERNVER"
 export KERNPREFIX=`echo "$KERNVER" | cut -c1`
 [ -z "$KERNSUFFIX" ] && KERNSUFFIX=1
-while [ -f /boot/vmlinuz-linux_"$KERNVER"\_"$KERNSUFFIX" ];
+while [ -f /boot/vmlinuz-linux_"$KERNVER"_"$KERNSUFFIX" ];
 do
 	export KERNSUFFIX=$((KERNSUFFIX+1))
 done
@@ -53,7 +53,7 @@ dlSource()
 ## Verbose download
 vdlSource()
 (
-	"$DLCOM"\v https://cdn.kernel.org/pub/linux/kernel/v"$KERNPREFIX".x/linux-"$KERNVER".tar.xz
+	"$DLCOM"v https://cdn.kernel.org/pub/linux/kernel/v"$KERNPREFIX".x/linux-"$KERNVER".tar.xz
 )
 
 ### Kernel confs
@@ -89,39 +89,39 @@ vrunMake()
 ### copy bzImage
 bzImg()
 (
-	sudo cp arch/"$UNAMEM"/boot/bzImage /boot/vmlinuz-linux_"$KERNVER"\_"$KERNSUFFIX"
+	sudo cp arch/"$UNAMEM"/boot/bzImage /boot/vmlinuz-linux_"$KERNVER"_"$KERNSUFFIX"
 )
 ## Verbose alternative copy bz
 vbzImg()
 (
-	sudo cp -v arch/"$UNAMEM"/boot/bzImage /boot/vmlinuz-linux_"$KERNVER"\_"$KERNSUFFIX"
+	sudo cp -v arch/"$UNAMEM"/boot/bzImage /boot/vmlinuz-linux_"$KERNVER"_"$KERNSUFFIX"
 )
 ### initramfs & systemmap
 initMap()
 (
-	sudo mkinitcpio -k "$KERNVER" -g /boot/initramfs-linux_"$KERNVER"\_"$KERNSUFFIX".img
-	sudo cp System.map /boot/System.map-linux_"$KERNVER"\_"$KERNSUFFIX"
+	sudo mkinitcpio -k "$KERNVER" -g /boot/initramfs-linux_"$KERNVER"_"$KERNSUFFIX".img
+	sudo cp System.map /boot/System.map-linux_"$KERNVER"_"$KERNSUFFIX"
 )
 ## Verbose alternative initramfs & systemmap
 vinitMap()
 (
-	sudo mkinitcpio -v -k "$KERNVER" -g /boot/initramfs-linux_"$KERNVER"\_"$KERNSUFFIX".img
-	sudo cp -v System.map /boot/System.map-linux_"$KERNVER"\_"$KERNSUFFIX"
+	sudo mkinitcpio -v -k "$KERNVER" -g /boot/initramfs-linux_"$KERNVER"_"$KERNSUFFIX".img
+	sudo cp -v System.map /boot/System.map-linux_"$KERNVER"_"$KERNSUFFIX"
 )
 
 ### Actually run the code
-[ ! -f linux-"$KERNVER".tar.xz ] && "$AUTOKERNVERB"\dlSource
-tar -x"$AUTOKERNVERB"\Jf linux-"$KERNVER".tar.xz || { echo "invalid kernel version"; exit 1; }
+[ ! -f linux-"$KERNVER".tar.xz ] && "$AUTOKERNVERB"dlSource
+tar -x"$AUTOKERNVERB"Jf linux-"$KERNVER".tar.xz || { echo "invalid kernel version"; exit 1; }
 cd linux-"$KERNVER" || return
-"$AUTOKERNVERB"\kernConf
+"$AUTOKERNVERB"kernConf
 ## Modify config
 read -p "Would you like to modify the kernel config? [y/N] " response
 case $response in [yY][eE][sS]|[yY]|[yY][eE])
 	make menuconfig;;
 esac
-"$AUTOKERNVERB"\runMake
-"$AUTOKERNVERB"\bzImg
-"$AUTOKERNVERB"\initMap
+"$AUTOKERNVERB"runMake
+"$AUTOKERNVERB"bzImg
+"$AUTOKERNVERB"initMap
 ## Update bootloader
 [ -f /boot/grub/grub.cfg ] && sudo grub-mkconfig -o /boot/grub/grub.cfg
 exit;
