update dependencies

diff --git a/autokern b/autokern
--- a/autokern
+++ b/autokern
@@ -1,6 +1,6 @@
 #!/bin/sh
 ### Set a couple variables
-type gcc make ld depmod perl bc openssl grub-mkconfig &> /dev/null || echo "The required programs are not installed, for more information, run 'autokern -h'"
+type gcc make ld depmod perl bc openssl grub-mkconfig mkinitcpio &> /dev/null || (echo "The required programs are not installed, for more information, run 'autokern -h'"; echo hi )
 export KERNDIR=$HOME\/.cache/autoKern
 export AUTOKERNCONF=$HOME\/.config/autoKern
 mkdir -p $KERNDIR
